// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdA-yECTh8UX4qb4_jfO89TTTj3OjGNQE',
    appId: '1:926010254735:web:739430d3a187db38dc97fa',
    messagingSenderId: '926010254735',
    projectId: 'smart-product-tracker',
    authDomain: 'smart-product-tracker.firebaseapp.com',
    storageBucket: 'smart-product-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3vQ18vPJ0hvLMZTN4NurFvq9giG7n8qU',
    appId: '1:926010254735:android:f2b3e617f384392adc97fa',
    messagingSenderId: '926010254735',
    projectId: 'smart-product-tracker',
    storageBucket: 'smart-product-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeDIetqeF32cAd-OB8IjjXE-t4uwe3TjE',
    appId: '1:926010254735:ios:ddc2f057e14173e2dc97fa',
    messagingSenderId: '926010254735',
    projectId: 'smart-product-tracker',
    storageBucket: 'smart-product-tracker.firebasestorage.app',
    iosBundleId: 'com.example.smartProductTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeDIetqeF32cAd-OB8IjjXE-t4uwe3TjE',
    appId: '1:926010254735:ios:ddc2f057e14173e2dc97fa',
    messagingSenderId: '926010254735',
    projectId: 'smart-product-tracker',
    storageBucket: 'smart-product-tracker.firebasestorage.app',
    iosBundleId: 'com.example.smartProductTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdA-yECTh8UX4qb4_jfO89TTTj3OjGNQE',
    appId: '1:926010254735:web:b60e8c83c5df9f3cdc97fa',
    messagingSenderId: '926010254735',
    projectId: 'smart-product-tracker',
    authDomain: 'smart-product-tracker.firebaseapp.com',
    storageBucket: 'smart-product-tracker.firebasestorage.app',
  );

}